name: FilamentGltfViewer
options:
    bundleIdPrefix: ${SAMPLE_CODE_DISAMBIGUATOR}.moineaufactory.filamentgltfviewer
targets:
    FilamentGltfViewerApp:
      type: application
      platform: iOS
      deploymentTarget: "12.1"
      info:
        path: FilamentGltfViewerApp/Info.plist
      sources:
        - path: FilamentGltfViewerApp
          type: folder
          buildPhase: sources
          excludes:
            - Info.plist

    FilamentGltfViewerAppStandalone:
      type: application
      platform: iOS
      deploymentTarget: "12.1"
      info:
        path: FilamentGltfViewerAppStandalone/Info.plist
      sources:
        - path: FilamentGltfViewerAppStandalone
          type: folder
          buildPhase: sources
          excludes:
            - Info.plist
        - path: 'Scene/'
          type: folder
          buildPhase: resources
        - path: 'generated/default_env/default_env_ibl.ktx'
          buildPhase: resources
          optional: true
        - path: 'generated/default_env/default_env_skybox.ktx'
          buildPhase: resources
          optional: true
      settings:
          base:
              SWIFT_OBJC_BRIDGING_HEADER: "FilamentGltfViewerAppStandalone/FilamentGltfViewer-Bridging-Header.h"
              OTHER_LDFLAGS: ["-lgltfio_core", "-luberarchive", "-limage", "-ldracodec", "-lmeshoptimizer",
                              "-lbasis_transcoder", "-lstb", "-lzstd", "-luberzlib"]
              ENABLE_BITCODE: NO
              CLANG_CXX_LANGUAGE_STANDARD: c++20
              # This allows users to not have to specify a unique bundle ID when building the sample apps.
              SAMPLE_CODE_DISAMBIGUATOR: ${DEVELOPMENT_TEAM}
      configs:
        debug:
          HEADER_SEARCH_PATHS: ["../filament/out/ios-debug/filament/include", "generated"]
          LIBRARY_SEARCH_PATHS:
            - "../filament/out/ios-debug/filament/lib/$(CURRENT_ARCH)"
            - "../filament/out/ios-debug/filament/lib/universal"
          release:
            HEADER_SEARCH_PATHS: ["../filament/out/ios-release/filament/include", "generated"]
            LIBRARY_SEARCH_PATHS:
              - "../filament/out/ios-release/filament/lib/$(CURRENT_ARCH)"
              - "../filament/out/ios-release/filament/lib/universal"
      preBuildScripts:
          - path: build-resources.sh
            name: Build Filament Resources