#ifndef RESOURCES_H_
#define RESOURCES_H_

#include <stdint.h>

extern "C" {
    extern const uint8_t RESOURCES_PACKAGE[];
}

#define RESOURCES_CUBE_OFFSET 0
#define RESOURCES_CUBE_SIZE 39353
#define RESOURCES_CUBE_DATA (RESOURCES_PACKAGE + RESOURCES_CUBE_OFFSET)

#define RESOURCES_CLEAR_COAT_OFFSET 39353
#define RESOURCES_CLEAR_COAT_SIZE 805587
#define RESOURCES_CLEAR_COAT_DATA (RESOURCES_PACKAGE + RESOURCES_CLEAR_COAT_OFFSET)

#define RESOURCES_SHADOW_PLANE_OFFSET 844940
#define RESOURCES_SHADOW_PLANE_SIZE 237433
#define RESOURCES_SHADOW_PLANE_DATA (RESOURCES_PACKAGE + RESOURCES_SHADOW_PLANE_OFFSET)

#define RESOURCES_CAMERA_FEED_OFFSET 1082373
#define RESOURCES_CAMERA_FEED_SIZE 58871
#define RESOURCES_CAMERA_FEED_DATA (RESOURCES_PACKAGE + RESOURCES_CAMERA_FEED_OFFSET)

#define RESOURCES_VENETIAN_CROSSROADS_2K_IBL_OFFSET 1141244
#define RESOURCES_VENETIAN_CROSSROADS_2K_IBL_SIZE 2095452
#define RESOURCES_VENETIAN_CROSSROADS_2K_IBL_DATA (RESOURCES_PACKAGE + RESOURCES_VENETIAN_CROSSROADS_2K_IBL_OFFSET)

#endif
